<?php

namespace AppBundle\Repository;

/**
 * SaveBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaveBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
