<?php

namespace AppBundle\Repository;

/**
 * TwigsBlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwigsBlocksRepository extends \Doctrine\ORM\EntityRepository
{
}
