<?php

namespace AppBundle\Repository;

/**
 * TwigsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwigsRepository extends \Doctrine\ORM\EntityRepository
{
}
