<?php

namespace AppBundle\Repository;

/**
 * WebPagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebPagesRepository extends \Doctrine\ORM\EntityRepository
{
}
